import { Category, MenuItem } from "@/types";

export const MENU_DATA: MenuItem[] = [
  // 국물류
  {
    id: 1,
    name: "김치찌개",
    emoji: "🍜",
    category: "soup",
    description: "집에서 끓인 것처럼 얼큰하고 깊은 맛",
    price: 3800,
    calories: 320,
    time: 5,
    spice: "매움",
    rating: 4.5,
  },
  {
    id: 2,
    name: "된장찌개",
    emoji: "🥣",
    category: "soup",
    description: "구수한 된장과 신선한 채소의 조화",
    price: 3500,
    calories: 280,
    time: 3,
    spice: "순함",
    rating: 4.2,
  },
  {
    id: 3,
    name: "부대찌개",
    emoji: "🍲",
    category: "soup",
    description: "햄, 소시지, 라면이 들어간 든든한 찌개",
    price: 4200,
    calories: 450,
    time: 7,
    spice: "보통",
    rating: 4.7,
  },
  // 튀김류
  {
    id: 4,
    name: "치킨까스",
    emoji: "🍗",
    category: "fried",
    description: "바삭한 치킨에 달콤한 소스",
    price: 5500,
    calories: 520,
    time: 8,
    spice: "마늘",
    rating: 4.8,
  },
  {
    id: 5,
    name: "생선까스",
    emoji: "🐟",
    category: "fried",
    description: "담백한 생선살로 만든 고소한 까스",
    price: 4800,
    calories: 380,
    time: 6,
    spice: "생선",
    rating: 4.3,
  },
  {
    id: 6,
    name: "새우튀김",
    emoji: "🍤",
    category: "fried",
    description: "통통한 새우를 바삭하게 튀긴 정식",
    price: 6200,
    calories: 420,
    time: 10,
    spice: "새우",
    rating: 4.6,
  },
  // 덮밥류
  {
    id: 7,
    name: "치킨마요덮밥",
    emoji: "🍛",
    category: "bowl",
    description: "바삭한 치킨과 크리미한 마요소스",
    price: 4500,
    calories: 580,
    time: 5,
    spice: "덮밥",
    rating: 4.9,
  },
  {
    id: 8,
    name: "불고기덮밥",
    emoji: "🥩",
    category: "bowl",
    description: "달콤한 불고기와 신선한 채소",
    price: 5200,
    calories: 490,
    time: 6,
    spice: "소고기",
    rating: 4.4,
  },
  {
    id: 9,
    name: "김치볶음밥",
    emoji: "🍳",
    category: "bowl",
    description: "매콤한 김치와 계란후라이",
    price: 3800,
    calories: 410,
    time: 4,
    spice: "매움",
    rating: 4.1,
  },
];

export const CATEGORIES: Category[] = [
  { key: "all", label: "전체", subtitle: "ALL" },
  { key: "soup", label: "국물", subtitle: "S" },
  { key: "fried", label: "튀김", subtitle: "F" },
  { key: "bowl", label: "덮밥", subtitle: "B" },
];
