import { MenuDetail } from "@/types";

export const MENU_DETAIL_DATA: { [key: number]: MenuDetail } = {
  // 국물류
  1: {
    id: 1,
    name: "김치찌개",
    emoji: "🍜",
    category: "soup",
    description: "집에서 끓인 것처럼 얼큰하고 깊은 맛",
    price: 3800,
    calories: 320,
    time: 5,
    spice: "매움",
    rating: 4.5,
    fullDescription:
      "묵은지와 돼지고기를 푹 끓여낸 정통 김치찌개입니다. 얼큰하면서도 깊은 맛이 일품이며, 두부와 파가 듬뿍 들어가 영양도 풍부합니다. 추운 날씨에 특히 인기가 많은 메뉴입니다.",
    reviewCount: 234,
    prepTime: 5,
    spiceLevel: "매움",
    servingSize: "1인분 (400ml)",
    nutrition: {
      calories: 320,
      carbs: 18,
      protein: 22,
      fat: 16,
      sodium: 1250,
      sugar: 4,
    },
    options: [
      {
        id: 1,
        name: "공기밥 추가",
        description: "흰쌀밥 1공기",
        price: 1000,
      },
      {
        id: 2,
        name: "라면사리 추가",
        description: "쫄깃한 라면사리",
        price: 800,
      },
      {
        id: 3,
        name: "치즈 토핑",
        description: "모짜렐라 치즈",
        price: 500,
      },
    ],
    reviews: [
      {
        id: 1,
        userName: "최*영",
        userAvatar: "👤",
        rating: 5.0,
        date: "1일 전",
        text: "진짜 집 김치찌개 맛이에요! 얼큰하니 해장에도 딱입니다 🔥",
      },
      {
        id: 2,
        userName: "정*우",
        userAvatar: "👤",
        rating: 4.0,
        date: "3일 전",
        text: "맛있는데 좀 짜요. 그래도 가성비는 최고!",
      },
      {
        id: 3,
        userName: "강*희",
        userAvatar: "👤",
        rating: 4.5,
        date: "1주 전",
        text: "고기도 많이 들어있고 국물이 진해요. 자주 먹는 메뉴입니다 👍",
      },
    ],
    badges: ["🔥 인기", "🌶️ 매운맛"],
    isPopular: true,
    isAIRecommended: false,
  },

  2: {
    id: 2,
    name: "된장찌개",
    emoji: "🥣",
    category: "soup",
    description: "구수한 된장과 신선한 채소의 조화",
    price: 3500,
    calories: 280,
    time: 3,
    spice: "순함",
    rating: 4.2,
    fullDescription:
      "국산 된장으로 만든 구수하고 건강한 찌개입니다. 두부, 애호박, 양파 등 신선한 채소가 듬뿍 들어있어 담백하고 속이 편안합니다. 매운 음식을 못 드시는 분들께 추천합니다.",
    reviewCount: 189,
    prepTime: 3,
    spiceLevel: "순함",
    servingSize: "1인분 (400ml)",
    nutrition: {
      calories: 280,
      carbs: 22,
      protein: 18,
      fat: 12,
      sodium: 980,
      sugar: 6,
    },
    options: [
      {
        id: 1,
        name: "공기밥 추가",
        description: "흰쌀밥 1공기",
        price: 1000,
      },
      {
        id: 2,
        name: "청양고추 추가",
        description: "얼큰하게 즐기기",
        price: 0,
      },
      {
        id: 3,
        name: "두부 추가",
        description: "부드러운 두부 1모",
        price: 500,
      },
    ],
    reviews: [
      {
        id: 1,
        userName: "송*진",
        userAvatar: "👤",
        rating: 4.5,
        date: "2일 전",
        text: "구수하고 담백해서 아침에 먹기 좋아요. 속도 편하고요!",
      },
      {
        id: 2,
        userName: "윤*서",
        userAvatar: "👤",
        rating: 4.0,
        date: "4일 전",
        text: "건강한 맛이에요. 매운 음식 먹다가 이거 먹으면 좋습니다.",
      },
      {
        id: 3,
        userName: "임*준",
        userAvatar: "👤",
        rating: 4.0,
        date: "1주 전",
        text: "집에서 먹는 된장찌개 같아요. 무난하게 맛있습니다 😊",
      },
    ],
    badges: ["🥬 건강식", "😌 순한맛"],
    isPopular: false,
    isAIRecommended: true,
  },

  3: {
    id: 3,
    name: "부대찌개",
    emoji: "🍲",
    category: "soup",
    description: "햄, 소시지, 라면이 들어간 든든한 찌개",
    price: 4200,
    calories: 450,
    time: 7,
    spice: "보통",
    rating: 4.7,
    fullDescription:
      "햄, 소시지, 라면사리, 떡, 김치가 푸짐하게 들어간 부대찌개입니다. 얼큰하면서도 달콤한 국물이 일품이며, 학생들에게 가장 인기 있는 메뉴 중 하나입니다. 2인분 주문도 가능합니다.",
    reviewCount: 312,
    prepTime: 7,
    spiceLevel: "보통",
    servingSize: "1인분 (500ml)",
    nutrition: {
      calories: 450,
      carbs: 48,
      protein: 24,
      fat: 18,
      sodium: 1450,
      sugar: 8,
    },
    options: [
      {
        id: 1,
        name: "공기밥 추가",
        description: "흰쌀밥 1공기",
        price: 1000,
      },
      {
        id: 2,
        name: "치즈 토핑",
        description: "쫄깃한 모짜렐라",
        price: 500,
      },
      {
        id: 3,
        name: "라면사리 추가",
        description: "사리 1개 추가",
        price: 800,
      },
      {
        id: 4,
        name: "2인분 세트",
        description: "양 2배, 밥 2공기",
        price: 3500,
      },
    ],
    reviews: [
      {
        id: 1,
        userName: "한*수",
        userAvatar: "👤",
        rating: 5.0,
        date: "오늘",
        text: "진짜 맛집! 양도 많고 국물도 끝내줘요. 친구랑 같이 먹기 좋아요 🔥",
      },
      {
        id: 2,
        userName: "오*아",
        userAvatar: "👤",
        rating: 4.5,
        date: "2일 전",
        text: "햄이랑 소시지가 많이 들어있어서 좋아요. 가격도 괜찮습니다!",
      },
      {
        id: 3,
        userName: "서*민",
        userAvatar: "👤",
        rating: 5.0,
        date: "5일 전",
        text: "학식 중에 최고! 치즈 토핑 추가하면 더 맛있어요 😋",
      },
    ],
    badges: ["🔥 인기", "👥 2인 추천", "AI 추천"],
    isPopular: true,
    isAIRecommended: true,
  },

  // 튀김류
  4: {
    id: 4,
    name: "치킨까스",
    emoji: "🍗",
    category: "fried",
    description: "바삭한 치킨에 달콤한 소스",
    price: 5500,
    calories: 520,
    time: 8,
    spice: "마늘",
    rating: 4.8,
    fullDescription:
      "두툼한 닭가슴살을 바삭하게 튀겨 달콤한 돈까스 소스와 함께 제공됩니다. 결대로 씹히는 치킨의 식감과 바삭한 튀김옷이 환상적인 조화를 이룹니다. 샐러드와 밥이 함께 제공됩니다.",
    reviewCount: 428,
    prepTime: 8,
    spiceLevel: "순함",
    servingSize: "1인분 (250g)",
    nutrition: {
      calories: 520,
      carbs: 42,
      protein: 38,
      fat: 22,
      sodium: 890,
      sugar: 12,
    },
    options: [
      {
        id: 1,
        name: "치즈 추가",
        description: "치즈까스 스타일",
        price: 500,
      },
      {
        id: 2,
        name: "소스 추가",
        description: "돈까스 소스 더블",
        price: 300,
      },
      {
        id: 3,
        name: "샐러드 대용량",
        description: "신선한 샐러드 2배",
        price: 1000,
      },
      {
        id: 4,
        name: "밥 곱배기",
        description: "밥 1.5배로",
        price: 500,
      },
    ],
    reviews: [
      {
        id: 1,
        userName: "문*영",
        userAvatar: "👤",
        rating: 5.0,
        date: "1일 전",
        text: "진짜 바삭하고 맛있어요! 학식이라고 무시하면 안 됩니다 👍👍",
      },
      {
        id: 2,
        userName: "배*호",
        userAvatar: "👤",
        rating: 5.0,
        date: "3일 전",
        text: "치킨이 두툼하고 육즙이 가득해요. 가격도 착해요!",
      },
      {
        id: 3,
        userName: "안*현",
        userAvatar: "👤",
        rating: 4.5,
        date: "1주 전",
        text: "소스가 달콤하니 맛있네요. 양도 푸짐합니다 😊",
      },
    ],
    badges: ["🔥 인기", "💪 고단백", "AI 추천"],
    isPopular: true,
    isAIRecommended: true,
  },

  5: {
    id: 5,
    name: "생선까스",
    emoji: "🐟",
    category: "fried",
    description: "담백한 생선살로 만든 고소한 까스",
    price: 4800,
    calories: 380,
    time: 6,
    spice: "생선",
    rating: 4.3,
    fullDescription:
      "신선한 흰살 생선을 사용한 건강한 생선까스입니다. 담백하고 부드러운 식감으로 느끼하지 않아 누구나 즐길 수 있습니다. 타르타르 소스와 레몬이 함께 제공되어 깔끔하게 즐기실 수 있습니다.",
    reviewCount: 156,
    prepTime: 6,
    spiceLevel: "순함",
    servingSize: "1인분 (200g)",
    nutrition: {
      calories: 380,
      carbs: 38,
      protein: 28,
      fat: 14,
      sodium: 720,
      sugar: 6,
    },
    options: [
      {
        id: 1,
        name: "타르타르 소스 추가",
        description: "고소한 타르타르",
        price: 500,
      },
      {
        id: 2,
        name: "레몬 추가",
        description: "신선한 레몬 2조각",
        price: 0,
      },
      {
        id: 3,
        name: "곁들임 추가",
        description: "감자튀김 추가",
        price: 1500,
      },
    ],
    reviews: [
      {
        id: 1,
        userName: "조*우",
        userAvatar: "👤",
        rating: 4.5,
        date: "2일 전",
        text: "생선 비린내 전혀 없고 담백해요. 다이어트 중인데 좋습니다!",
      },
      {
        id: 2,
        userName: "황*미",
        userAvatar: "👤",
        rating: 4.0,
        date: "5일 전",
        text: "타르타르 소스랑 같이 먹으면 맛있어요. 건강한 맛!",
      },
      {
        id: 3,
        userName: "권*석",
        userAvatar: "👤",
        rating: 4.5,
        date: "1주 전",
        text: "생선이 부드럽고 튀김이 바삭해요 👍",
      },
    ],
    badges: ["🥬 건강식", "💪 고단백"],
    isPopular: false,
    isAIRecommended: true,
  },

  6: {
    id: 6,
    name: "새우튀김",
    emoji: "🍤",
    category: "fried",
    description: "통통한 새우를 바삭하게 튀긴 정식",
    price: 6200,
    calories: 420,
    time: 10,
    spice: "새우",
    rating: 4.6,
    fullDescription:
      "대왕 새우를 튀김옷에 입혀 바삭하게 튀긴 프리미엄 메뉴입니다. 큼직한 새우 5마리가 제공되며, 특제 칠리 소스와 함께 즐기실 수 있습니다. 텐동 스타일의 소스를 선택할 수도 있습니다.",
    reviewCount: 267,
    prepTime: 10,
    spiceLevel: "순함",
    servingSize: "1인분 (새우 5마리)",
    nutrition: {
      calories: 420,
      carbs: 36,
      protein: 32,
      fat: 16,
      sodium: 850,
      sugar: 8,
    },
    options: [
      {
        id: 1,
        name: "새우 추가",
        description: "새우 2마리 추가",
        price: 2000,
      },
      {
        id: 2,
        name: "텐동 소스",
        description: "달콤한 일본식 소스",
        price: 0,
      },
      {
        id: 3,
        name: "야채튀김 추가",
        description: "고구마, 가지 튀김",
        price: 1500,
      },
      {
        id: 4,
        name: "우동 세트",
        description: "따뜻한 우동 추가",
        price: 2000,
      },
    ],
    reviews: [
      {
        id: 1,
        userName: "신*은",
        userAvatar: "👤",
        rating: 5.0,
        date: "오늘",
        text: "새우가 진짜 통통하고 맛있어요! 가격값 해요 🍤🍤",
      },
      {
        id: 2,
        userName: "유*호",
        userAvatar: "👤",
        rating: 4.5,
        date: "3일 전",
        text: "튀김이 바삭하고 새우가 크네요. 텐동 소스 추천합니다!",
      },
      {
        id: 3,
        userName: "장*아",
        userAvatar: "👤",
        rating: 4.5,
        date: "6일 전",
        text: "좀 비싸긴 한데 맛은 확실해요. 특별한 날 먹기 좋아요 😋",
      },
    ],
    badges: ["⭐ 프리미엄", "💪 고단백"],
    isPopular: false,
    isAIRecommended: false,
  },

  // 덮밥류
  7: {
    id: 7,
    name: "치킨마요덮밥",
    emoji: "🍛",
    category: "bowl",
    description: "바삭한 치킨과 크리미한 마요소스",
    price: 4500,
    calories: 580,
    time: 5,
    spice: "덮밥",
    rating: 4.9,
    fullDescription:
      "바삭하게 튀긴 치킨과 크리미한 마요네즈 소스가 어우러진 인기 메뉴입니다. 신선한 양배추채와 함께 든든한 한 끼 식사로 완벽합니다. 학생들이 가장 많이 찾는 베스트 메뉴입니다.",
    reviewCount: 521,
    prepTime: 5,
    spiceLevel: "순함",
    servingSize: "1인분",
    nutrition: {
      calories: 580,
      carbs: 65,
      protein: 28,
      fat: 18,
      sodium: 820,
      sugar: 8,
    },
    options: [
      {
        id: 1,
        name: "치즈 추가",
        description: "고소한 모짜렐라 치즈",
        price: 500,
      },
      {
        id: 2,
        name: "계란 후라이 추가",
        description: "반숙 계란 후라이",
        price: 500,
      },
      {
        id: 3,
        name: "대용량",
        description: "1.5배 양으로 제공",
        price: 1000,
      },
      {
        id: 4,
        name: "매콤하게",
        description: "칠리소스 추가",
        price: 0,
      },
    ],
    reviews: [
      {
        id: 1,
        userName: "김*현",
        userAvatar: "👤",
        rating: 5.0,
        date: "2일 전",
        text: "치킨이 정말 바삭하고 소스도 맛있어요! 학식 중에서 제일 자주 먹는 메뉴입니다 👍",
      },
      {
        id: 2,
        userName: "이*주",
        userAvatar: "👤",
        rating: 4.5,
        date: "5일 전",
        text: "가격 대비 양도 많고 맛도 좋아요. 다만 점심시간엔 대기가 좀 있어요.",
      },
      {
        id: 3,
        userName: "박*민",
        userAvatar: "👤",
        rating: 5.0,
        date: "1주 전",
        text: "마요 소스가 진짜 맛있어요! 치킨도 바삭바삭하고 최고입니다 🔥",
      },
    ],
    badges: ["🔥 인기", "🏆 베스트", "AI 추천"],
    isPopular: true,
    isAIRecommended: true,
  },

  8: {
    id: 8,
    name: "불고기덮밥",
    emoji: "🥩",
    category: "bowl",
    description: "달콤한 불고기와 신선한 채소",
    price: 5200,
    calories: 490,
    time: 6,
    spice: "소고기",
    rating: 4.4,
    fullDescription:
      "달콤하게 양념한 소고기 불고기와 신선한 채소를 밥 위에 얹은 메뉴입니다. 양파, 당근, 파프리카 등 다양한 채소가 들어가 영양 밸런스가 좋습니다. 고추장을 추가하면 비빔밥 스타일로도 즐길 수 있습니다.",
    reviewCount: 198,
    prepTime: 6,
    spiceLevel: "순함",
    servingSize: "1인분",
    nutrition: {
      calories: 490,
      carbs: 58,
      protein: 32,
      fat: 14,
      sodium: 950,
      sugar: 12,
    },
    options: [
      {
        id: 1,
        name: "고기 추가",
        description: "불고기 50g 추가",
        price: 2000,
      },
      {
        id: 2,
        name: "고추장 추가",
        description: "비빔밥 스타일",
        price: 0,
      },
      {
        id: 3,
        name: "계란 후라이",
        description: "반숙 계란",
        price: 500,
      },
      {
        id: 4,
        name: "김가루 추가",
        description: "고소한 김가루",
        price: 0,
      },
    ],
    reviews: [
      {
        id: 1,
        userName: "최*진",
        userAvatar: "👤",
        rating: 4.5,
        date: "1일 전",
        text: "불고기가 달콤하고 부드러워요. 고기 양도 적당합니다!",
      },
      {
        id: 2,
        userName: "정*연",
        userAvatar: "👤",
        rating: 4.5,
        date: "4일 전",
        text: "채소도 신선하고 맛있어요. 고추장 넣으면 비빔밥 되네요 😊",
      },
      {
        id: 3,
        userName: "강*우",
        userAvatar: "👤",
        rating: 4.0,
        date: "1주 전",
        text: "무난하게 맛있습니다. 가끔 먹기 좋아요.",
      },
    ],
    badges: ["💪 고단백", "AI 추천"],
    isPopular: false,
    isAIRecommended: true,
  },

  9: {
    id: 9,
    name: "김치볶음밥",
    emoji: "🍳",
    category: "bowl",
    description: "매콤한 김치와 계란후라이",
    price: 3800,
    calories: 410,
    time: 4,
    spice: "매움",
    rating: 4.1,
    fullDescription:
      "잘 익은 김치로 볶아낸 얼큰한 볶음밥입니다. 계란 후라이가 토핑으로 올라가며, 김가루와 참기름으로 마무리됩니다. 간단하지만 속이 든든하고 가성비가 좋은 메뉴입니다.",
    reviewCount: 145,
    prepTime: 4,
    spiceLevel: "매움",
    servingSize: "1인분",
    nutrition: {
      calories: 410,
      carbs: 62,
      protein: 14,
      fat: 12,
      sodium: 1150,
      sugar: 6,
    },
    options: [
      {
        id: 1,
        name: "치즈 추가",
        description: "모짜렐라 치즈",
        price: 500,
      },
      {
        id: 2,
        name: "계란 추가",
        description: "계란 후라이 1개 더",
        price: 500,
      },
      {
        id: 3,
        name: "햄 추가",
        description: "스팸 50g",
        price: 1000,
      },
      {
        id: 4,
        name: "대용량",
        description: "1.5배 양",
        price: 1000,
      },
    ],
    reviews: [
      {
        id: 1,
        userName: "송*희",
        userAvatar: "👤",
        rating: 4.5,
        date: "2일 전",
        text: "간단하게 먹기 좋아요. 김치가 적당히 매콤해요 🌶️",
      },
      {
        id: 2,
        userName: "윤*민",
        userAvatar: "👤",
        rating: 4.0,
        date: "5일 전",
        text: "가성비 좋고 빨리 나와요. 치즈 추가 강추!",
      },
      {
        id: 3,
        userName: "임*수",
        userAvatar: "👤",
        rating: 3.5,
        date: "1주 전",
        text: "맛은 있는데 양이 좀 적은 것 같아요. 남자는 대용량 추천.",
      },
    ],
    badges: ["⚡ 빠른 조리", "🌶️ 매운맛", "💰 가성비"],
    isPopular: false,
    isAIRecommended: false,
  },
};

// import { MenuDetail } from "@/types";

// export const MENU_DETAIL_DATA: { [key: number]: MenuDetail } = {
//   7: {
//     id: 7,
//     name: "치킨마요덮밥",
//     emoji: "🍛",
//     category: "bowl",
//     description: "바삭한 치킨과 크리미한 마요소스",
//     price: 4500,
//     calories: 580,
//     time: 5,
//     spice: "덮밥",
//     rating: 4.9,
//     fullDescription:
//       "바삭하게 튀긴 치킨과 크리미한 마요네즈 소스가 어우러진 인기 메뉴입니다. 신선한 채소와 함께 든든한 한 끼 식사로 완벽합니다.",
//     reviewCount: 127,
//     prepTime: 5,
//     spiceLevel: "순함",
//     servingSize: "1인분",
//     nutrition: {
//       calories: 580,
//       carbs: 65,
//       protein: 28,
//       fat: 18,
//       sodium: 820,
//       sugar: 8,
//     },
//     options: [
//       {
//         id: 1,
//         name: "치즈 추가",
//         description: "고소한 모짜렐라 치즈",
//         price: 500,
//       },
//       {
//         id: 2,
//         name: "계란 후라이 추가",
//         description: "반숙 계란 후라이",
//         price: 500,
//       },
//       { id: 3, name: "대용량", description: "1.5배 양으로 제공", price: 1000 },
//     ],
//     reviews: [
//       {
//         id: 1,
//         userName: "김*현",
//         userAvatar: "👤",
//         rating: 5.0,
//         date: "2일 전",
//         text: "치킨이 정말 바삭하고 소스도 맛있어요! 학식 중에서 제일 자주 먹는 메뉴입니다 👍",
//       },
//       {
//         id: 2,
//         userName: "이*주",
//         userAvatar: "👤",
//         rating: 4.5,
//         date: "5일 전",
//         text: "가격 대비 양도 많고 맛도 좋아요. 다만 점심시간엔 대기가 좀 있어요.",
//       },
//       {
//         id: 3,
//         userName: "박*민",
//         userAvatar: "👤",
//         rating: 5.0,
//         date: "1주 전",
//         text: "마요 소스가 진짜 맛있어요! 치킨도 바삭바삭하고 최고입니다 🔥",
//       },
//     ],
//     badges: ["🔥 인기", "AI 추천"],
//     isPopular: true,
//     isAIRecommended: true,
//   },
// };
