import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#FFFFFF",
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 20,
    backgroundColor: "#FFFFFF",
    borderBottomWidth: 1,
    borderBottomColor: "#E8EAED",
  },
  backButton: {
    width: 40,
    height: 40,
    backgroundColor: "#F1F3F4",
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
  },
  backButtonText: {
    fontSize: 18,
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: "700",
  },
  clearButton: {
    color: "#0066FF",
    fontSize: 14,
    fontWeight: "600",
    padding: 8,
  },
  scrollContent: {
    paddingBottom: 200,
  },
  emptyState: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    padding: 80,
  },
  emptyIcon: {
    fontSize: 80,
    marginBottom: 20,
    opacity: 0.3,
  },
  emptyTitle: {
    fontSize: 20,
    fontWeight: "700",
    marginBottom: 8,
    color: "#3C4043",
  },
  emptyDescription: {
    color: "#5F6368",
    marginBottom: 24,
  },
  emptyButton: {
    backgroundColor: "#0066FF",
    borderRadius: 16,
    paddingVertical: 16,
    paddingHorizontal: 32,
  },
  emptyButtonText: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "600",
  },
  cartContent: {
    padding: 20,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "700",
    marginBottom: 16,
    color: "#1A1A1A",
    flexDirection: "row",
    alignItems: "center",
  },
  badge: {
    backgroundColor: "#FFD700",
    color: "#1A1A1A",
    fontSize: 11,
    fontWeight: "700",
    paddingVertical: 4,
    paddingHorizontal: 8,
    borderRadius: 6,
    marginLeft: 8,
    marginBottom: 16,
  },
  cartItem: {
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#E8EAED",
    borderRadius: 16,
    padding: 16,
    marginBottom: 12,
  },
  itemHeader: {
    flexDirection: "row",
    gap: 16,
    marginBottom: 12,
  },
  itemImage: {
    width: 70,
    height: 70,
    backgroundColor: "#FFD700",
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  itemEmoji: {
    fontSize: 32,
  },
  itemInfo: {
    flex: 1,
  },
  itemName: {
    fontSize: 16,
    fontWeight: "700",
    marginBottom: 4,
  },
  itemDescription: {
    fontSize: 13,
    color: "#5F6368",
    marginBottom: 8,
  },
  itemPrice: {
    fontSize: 16,
    fontWeight: "700",
    color: "#0066FF",
  },
  removeButton: {
    padding: 8,
  },
  removeButtonText: {
    fontSize: 20,
    color: "#5F6368",
  },
  itemActions: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  quantityControls: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    backgroundColor: "#F8F9FA",
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 12,
  },
  quantityButton: {
    width: 28,
    height: 28,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#DADCE0",
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
  },
  quantityButtonText: {
    fontSize: 16,
    fontWeight: "600",
    color: "#3C4043",
  },
  quantityValue: {
    fontSize: 16,
    fontWeight: "700",
    minWidth: 24,
    textAlign: "center",
  },
  itemTotal: {
    fontSize: 16,
    fontWeight: "700",
    color: "#1A1A1A",
  },
  optionsSection: {
    marginTop: 24,
    paddingTop: 24,
    borderTopWidth: 1,
    borderTopColor: "#E8EAED",
  },
  optionItem: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 12,
  },
  optionLabel: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  optionIcon: {
    fontSize: 18,
  },
  optionText: {
    fontSize: 15,
    color: "#3C4043",
  },
  optionToggle: {
    width: 48,
    height: 28,
    backgroundColor: "#DADCE0",
    borderRadius: 14,
    justifyContent: "center",
    padding: 3,
  },
  optionToggleActive: {
    backgroundColor: "#0066FF",
  },
  optionToggleThumb: {
    width: 22,
    height: 22,
    backgroundColor: "#FFFFFF",
    borderRadius: 11,
  },
  optionToggleThumbActive: {
    alignSelf: "flex-end",
  },
  summarySection: {
    backgroundColor: "#F8F9FA",
    borderRadius: 16,
    padding: 20,
    marginTop: 24,
  },
  summaryRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  summaryLabel: {
    fontSize: 15,
    color: "#3C4043",
  },
  summaryValue: {
    fontSize: 15,
    fontWeight: "600",
    color: "#1A1A1A",
  },
  summaryDiscount: {
    color: "#DC2626",
  },
  summaryDivider: {
    height: 1,
    backgroundColor: "#DADCE0",
    marginVertical: 16,
  },
  summaryTotal: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  totalLabel: {
    fontSize: 18,
    fontWeight: "700",
    color: "#1A1A1A",
  },
  totalAmount: {
    fontSize: 24,
    fontWeight: "700",
    color: "#0066FF",
  },
  bottomAction: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: "#FFFFFF",
    padding: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.1,
    shadowRadius: 20,
    elevation: 10,
    borderTopWidth: 1,
    borderTopColor: "#E8EAED",
  },
  pickupInfo: {
    backgroundColor: "#E8EAED",
    borderRadius: 16,
    padding: 16,
    marginBottom: 16,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  pickupIcon: {
    fontSize: 24,
  },
  pickupDetails: {
    flex: 1,
  },
  pickupTitle: {
    fontSize: 14,
    fontWeight: "700",
    marginBottom: 4,
    color: "#1A1A1A",
  },
  pickupLocation: {
    fontSize: 13,
    color: "#3C4043",
  },
  orderButton: {
    width: "100%",
    backgroundColor: "#0066FF",
    borderRadius: 16,
    padding: 18,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: 8,
  },
  orderButtonText: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "700",
  },
  orderButtonTotal: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "700",
  },
});
