import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#FFFFFF",
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 20,
    borderBottomWidth: 1,
    backgroundColor: "#FFFFFF",
    borderBottomColor: "#E8EAED",
  },
  backButton: {
    width: 40,
    height: 40,
    backgroundColor: "#F1F3F4",
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
  },
  backButtonText: {
    fontSize: 18,
  },
  headerActions: {
    flexDirection: "row",
    gap: 12,
  },
  iconButton: {
    width: 40,
    height: 40,
    backgroundColor: "#F1F3F4",
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
  },
  iconButtonText: {
    fontSize: 18,
  },
  cartButton: {
    width: 40,
    height: 40,
    backgroundColor: "#F1F3F4",
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
  },
  cartButtonText: {
    fontSize: 18,
  },
  heroSection: {
    height: 300,
    backgroundColor: "#FFD700",
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
  },
  heroEmoji: {
    fontSize: 120,
  },
  badgeContainer: {
    position: "absolute",
    top: 20,
    left: 20,
    flexDirection: "row",
    gap: 8,
  },
  badge: {
    backgroundColor: "rgba(255, 255, 255, 0.95)",
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 20,
    fontSize: 14,
    fontWeight: "600",
  },
  contentSection: {
    padding: 24,
    paddingBottom: 120,
  },
  menuCategory: {
    color: "#5F6368",
    fontSize: 14,
    marginBottom: 8,
  },
  menuTitle: {
    fontSize: 28,
    fontWeight: "700",
    marginBottom: 12,
    color: "#1A1A1A",
  },
  ratingContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    marginBottom: 16,
  },
  ratingStars: {
    fontSize: 16,
    fontWeight: "700",
    color: "#FFD700",
  },
  ratingCount: {
    color: "#5F6368",
    fontSize: 14,
  },
  menuPrice: {
    fontSize: 32,
    fontWeight: "700",
    color: "#0066FF",
    marginBottom: 24,
  },
  menuDescription: {
    color: "#5F6368",
    lineHeight: 24,
    marginBottom: 32,
  },
  infoCards: {
    flexDirection: "row",
    gap: 12,
    marginBottom: 32,
  },
  infoCard: {
    flex: 1,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#E8EAED",
    borderRadius: 16,
    padding: 16,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 3,
  },
  infoIcon: {
    fontSize: 24,
    marginBottom: 8,
  },
  infoValue: {
    fontSize: 16,
    fontWeight: "700",
    color: "#1A1A1A",
    marginBottom: 4,
  },
  infoLabel: {
    fontSize: 12,
    color: "#5F6368",
  },
  section: {
    marginBottom: 32,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: "700",
    marginBottom: 16,
    color: "#1A1A1A",
  },
  nutritionGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
  },
  nutritionItem: {
    width: "48%",
    backgroundColor: "#F8F9FA",
    borderRadius: 16,
    padding: 16,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  nutritionLabel: {
    color: "#3C4043",
    fontWeight: "500",
  },
  nutritionValue: {
    fontWeight: "700",
    color: "#0066FF",
  },
  optionItem: {
    backgroundColor: "#FFFFFF",
    borderWidth: 2,
    borderColor: "#E8EAED",
    borderRadius: 16,
    padding: 16,
    marginBottom: 12,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  optionItemSelected: {
    borderColor: "#0066FF",
    backgroundColor: "#F0F7FF",
  },
  optionInfo: {
    flex: 1,
  },
  optionName: {
    fontWeight: "600",
    marginBottom: 4,
    color: "#1A1A1A",
  },
  optionDesc: {
    fontSize: 13,
    color: "#5F6368",
  },
  optionPrice: {
    fontWeight: "700",
    color: "#0066FF",
  },
  quantitySection: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    padding: 20,
    backgroundColor: "#F8F9FA",
    borderRadius: 16,
    marginBottom: 24,
  },
  quantityLabel: {
    fontWeight: "600",
    fontSize: 16,
  },
  quantityControls: {
    flexDirection: "row",
    alignItems: "center",
    gap: 16,
  },
  quantityButton: {
    width: 36,
    height: 36,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#DADCE0",
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
  },
  quantityButtonText: {
    fontSize: 18,
    fontWeight: "600",
    color: "#1A1A1A",
  },
  quantityValue: {
    fontSize: 18,
    fontWeight: "700",
    minWidth: 30,
    textAlign: "center",
  },
  reviewItem: {
    backgroundColor: "#F8F9FA",
    borderRadius: 16,
    padding: 16,
    marginBottom: 12,
  },
  reviewHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  reviewerInfo: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  reviewerAvatar: {
    width: 40,
    height: 40,
    backgroundColor: "#FFD700",
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    fontSize: 18,
  },
  reviewerName: {
    fontWeight: "600",
    marginBottom: 2,
  },
  reviewDate: {
    fontSize: 12,
    color: "#5F6368",
  },
  reviewRating: {
    fontWeight: "600",
    color: "#FFD700",
  },
  reviewText: {
    color: "#3C4043",
    lineHeight: 21,
  },
  bottomAction: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: "#FFFFFF",
    padding: 20,
    flexDirection: "row",
    gap: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.1,
    shadowRadius: 20,
    elevation: 10,
  },
  totalPrice: {
    flex: 1,
    justifyContent: "center",
  },
  totalLabel: {
    fontSize: 12,
    color: "#5F6368",
    marginBottom: 4,
  },
  totalAmount: {
    fontSize: 24,
    fontWeight: "700",
    color: "#0066FF",
  },
  addToCartButton: {
    flex: 2,
    backgroundColor: "#0066FF",
    borderRadius: 16,
    padding: 18,
    alignItems: "center",
    justifyContent: "center",
  },
  addToCartButtonText: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "700",
  },
  scrollContent: {
    paddingBottom: 100,
  },
});
