import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#FFFFFF",
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 20,
    backgroundColor: "#FFFFFF",
    borderBottomWidth: 1,
    borderBottomColor: "#E8EAED",
  },
  backButton: {
    width: 40,
    height: 40,
    backgroundColor: "#F1F3F4",
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
  },
  backButtonText: {
    fontSize: 18,
  },
  orderNumber: {
    fontWeight: "700",
    color: "#3C4043",
  },
  helpButton: {
    width: 40,
    height: 40,
    backgroundColor: "#F1F3F4",
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
  },
  helpButtonText: {
    fontSize: 18,
  },
  scrollContent: {
    paddingBottom: 100,
  },
  statusHero: {
    padding: 40,
    alignItems: "center",
    backgroundColor: "#F8F9FA",
  },
  statusAnimation: {
    width: 160,
    height: 160,
    backgroundColor: "#FFD700",
    borderRadius: 80,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 24,
    shadowColor: "#FFD700",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.3,
    shadowRadius: 30,
    elevation: 8,
  },
  statusRing: {
    position: "absolute",
    top: -10,
    left: -10,
    right: -10,
    bottom: -10,
    borderWidth: 3,
    borderColor: "transparent",
    borderTopColor: "#0066FF",
    borderRadius: 90, // (160 + 20) / 2
  },
  statusEmoji: {
    fontSize: 80,
  },
  statusTitle: {
    fontSize: 28,
    fontWeight: "700",
    marginBottom: 12,
    color: "#0066FF",
    textAlign: "center",
  },
  statusSubtitle: {
    fontSize: 16,
    color: "#5F6368",
    marginBottom: 24,
    textAlign: "center",
  },
  estimatedTime: {
    backgroundColor: "#0066FF",
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 30,
    shadowColor: "#0066FF",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 12,
    elevation: 4,
  },
  estimatedTimeText: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "600",
  },
  progressContainer: {
    padding: 40,
  },
  progressStep: {
    flexDirection: "row",
    alignItems: "flex-start",
    marginBottom: 32,
  },
  stepIconContainer: {
    width: 48,
    height: 48,
    borderRadius: 24,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 16,
    backgroundColor: "#F1F3F4",
    borderWidth: 2,
    borderColor: "#E8EAED",
  },
  stepIconCompleted: {
    backgroundColor: "#0066FF",
    borderColor: "#0066FF",
  },
  stepIconActive: {
    backgroundColor: "#FFD700",
    borderColor: "#FFD700",
  },
  stepIcon: {
    fontSize: 24,
    color: "#ffffff",
  },
  stepContent: {
    flex: 1,
    paddingTop: 8,
  },
  stepTitle: {
    fontSize: 18,
    fontWeight: "600",
    marginBottom: 4,
    color: "#1A1A1A",
  },
  stepTime: {
    fontSize: 14,
    color: "#5F6368",
  },
  stepTitleCompleted: {
    color: "#5F6368",
  },
  stepTitleActive: {
    color: "#0066FF",
  },
  orderDetails: {
    padding: 20,
    paddingBottom: 40,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: "700",
    marginBottom: 16,
    color: "#1A1A1A",
  },
  orderCard: {
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#E8EAED",
    borderRadius: 16,
    padding: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 3,
  },
  orderItem: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 16,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#F1F3F4",
  },
  orderItemLast: {
    marginBottom: 0,
    paddingBottom: 0,
    borderBottomWidth: 0,
  },
  statusAnimationReady: {
    backgroundColor: "#FFD700",
  },
  statusTitleReady: {
    color: "#FFD700",
  },
  estimatedTimeReady: {
    backgroundColor: "#FFD700",
  },
  estimatedTimeTextReady: {
    color: "#1A1A1A",
  },
  itemImage: {
    width: 60,
    height: 60,
    backgroundColor: "#FFD700",
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 16,
  },
  itemEmoji: {
    fontSize: 28,
  },
  itemInfo: {
    flex: 1,
  },
  itemName: {
    fontWeight: "600",
    marginBottom: 4,
  },
  itemOptions: {
    fontSize: 13,
    color: "#5F6368",
  },
  itemPrice: {
    fontWeight: "700",
    color: "#0066FF",
  },
  locationCard: {
    backgroundColor: "#F8F9FA",
    borderRadius: 16,
    padding: 20,
    marginTop: 20,
    flexDirection: "row",
    alignItems: "center",
    gap: 16,
  },
  locationIcon: {
    width: 48,
    height: 48,
    backgroundColor: "#0066FF",
    borderRadius: 24,
    alignItems: "center",
    justifyContent: "center",
  },
  locationIconText: {
    fontSize: 24,
    color: "#FFFFFF",
  },
  locationInfo: {
    flex: 1,
  },
  locationTitle: {
    fontWeight: "600",
    marginBottom: 4,
  },
  locationAddress: {
    fontSize: 14,
    color: "#5F6368",
  },
  miniGameSection: {
    padding: 40,
    backgroundColor: "#F8F9FA",
    alignItems: "center",
  },
  gameCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 20,
    padding: 30,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 3,
    width: "100%",
    alignItems: "center",
  },
  gameTitle: {
    fontSize: 20,
    fontWeight: "700",
    marginBottom: 12,
  },
  gameSubtitle: {
    fontSize: 14,
    color: "#5F6368",
    marginBottom: 24,
    textAlign: "center",
  },
  gameButton: {
    backgroundColor: "#FFD700",
    borderRadius: 16,
    paddingVertical: 16,
    paddingHorizontal: 32,
    shadowColor: "#FFD700",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 12,
    elevation: 4,
  },
  gameButtonText: {
    color: "#1A1A1A",
    fontSize: 16,
    fontWeight: "700",
  },
  rewardBadge: {
    backgroundColor: "#0066FF",
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 20,
    marginTop: 16,
  },
  rewardBadgeText: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "600",
  },
  bottomAction: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: "#FFFFFF",
    padding: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.1,
    shadowRadius: 20,
    elevation: 10,
  },
  cancelButton: {
    width: "100%",
    backgroundColor: "#FFFFFF",
    borderWidth: 2,
    borderColor: "#DADCE0",
    borderRadius: 16,
    padding: 16,
    alignItems: "center",
  },
  cancelButtonText: {
    color: "#3C4043",
    fontSize: 16,
    fontWeight: "600",
  },
  pickupButton: {
    width: "100%",
    backgroundColor: "#0066FF",
    borderWidth: 2,
    borderColor: "#DADCE0",
    borderRadius: 16,
    padding: 16,
    alignItems: "center",
  },
  pickupButtonText: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "600",
  },
  loadingDots: {
    flexDirection: "row",
    gap: 4,
    marginLeft: 6,
    marginBottom: 24,
  },
  dot: {
    width: 6,
    height: 6,
    backgroundColor: "#0066FF",
    borderRadius: 3,
  },
});
