import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#FFFFFF",
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 20,
    backgroundColor: "#FFFFFF",
    borderBottomWidth: 1,
    borderBottomColor: "#E8EAED",
  },
  closeButton: {
    width: 40,
    height: 40,
    backgroundColor: "#F1F3F4",
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
  },
  closeButtonText: {
    fontSize: 20,
  },
  headerTitle: {
    fontWeight: "700",
    fontSize: 16,
    color: "#3C4043",
  },
  shareButton: {
    width: 40,
    height: 40,
    backgroundColor: "#F1F3F4",
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
  },
  shareButtonText: {
    fontSize: 18,
  },
  scrollContent: {
    paddingBottom: 120,
  },
  successHero: {
    padding: 40,
    alignItems: "center",
    backgroundColor: "#F8F9FA",
  },
  successAnimation: {
    width: 160,
    height: 160,
    backgroundColor: "#10B981",
    borderRadius: 80,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 24,
    shadowColor: "#10B981",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.3,
    shadowRadius: 30,
    elevation: 8,
  },
  successEmoji: {
    fontSize: 80,
  },
  successRing: {
    position: "absolute",
    top: -15,
    left: -15,
    right: -15,
    bottom: -15,
    borderWidth: 3,
    borderColor: "#10B981",
    borderRadius: 87.5,
  },
  successTitle: {
    fontSize: 28,
    fontWeight: "700",
    marginBottom: 12,
    color: "#10B981",
    textAlign: "center",
  },
  successSubtitle: {
    fontSize: 16,
    color: "#5F6368",
    marginBottom: 24,
    textAlign: "center",
  },
  successBadge: {
    backgroundColor: "#FFD700",
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 30,
    shadowColor: "#FFD700",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 12,
    elevation: 4,
  },
  successBadgeText: {
    color: "#1A1A1A",
    fontSize: 15,
    fontWeight: "600",
  },
  statsSection: {
    padding: 20,
    paddingBottom: 40,
  },
  statsGrid: {
    flexDirection: "row",
    gap: 12,
  },
  statCard: {
    flex: 1,
    flexShrink: 1,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#E8EAED",
    borderRadius: 16,
    padding: 16,
    textAlign: "center",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 3,
  },
  statIcon: {
    fontSize: 32,
    marginBottom: 8,
  },
  statValue: {
    fontSize: 18,
    fontWeight: "700",
    color: "#0066FF",
    marginBottom: 4,
  },
  statLabel: {
    fontSize: 12,
    color: "#5F6368",
  },
  orderSummary: {
    padding: 20,
    paddingBottom: 40,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: "700",
    marginBottom: 16,
    color: "#1A1A1A",
  },
  summaryCard: {
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#E8EAED",
    borderRadius: 16,
    padding: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 3,
  },
  summaryHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#E8EAED",
    marginBottom: 16,
  },
  orderNumber: {
    fontSize: 14,
    color: "#5F6368",
  },
  orderDate: {
    fontSize: 14,
    color: "#5F6368",
  },
  orderItem: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 16,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#F1F3F4",
  },
  orderItemLast: {
    marginBottom: 0,
    paddingBottom: 0,
    borderBottomWidth: 0,
  },
  itemImage: {
    width: 60,
    height: 60,
    backgroundColor: "#FFD700",
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 16,
  },
  itemEmoji: {
    fontSize: 28,
  },
  itemInfo: {
    flex: 1,
  },
  itemName: {
    fontWeight: "600",
    marginBottom: 4,
    fontSize: 16,
  },
  itemQuantity: {
    fontSize: 13,
    color: "#5F6368",
  },
  itemPrice: {
    fontWeight: "700",
    fontSize: 16,
    color: "#1A1A1A",
  },
  totalSection: {
    backgroundColor: "#F8F9FA",
    borderRadius: 16,
    padding: 16,
    marginTop: 20,
  },
  totalRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 8,
  },
  totalRowLast: {
    marginBottom: 0,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: "#DADCE0",
    marginTop: 12,
  },
  totalLabel: {
    fontSize: 15,
    color: "#3C4043",
  },
  totalValue: {
    fontSize: 15,
    fontWeight: "600",
    color: "#1A1A1A",
  },
  totalDiscount: {
    color: "#DC2626",
  },
  totalFinal: {
    fontSize: 20,
    fontWeight: "700",
    color: "#0066FF",
  },
  pointsCard: {
    backgroundColor: "#FFD700",
    borderRadius: 16,
    padding: 20,
    marginTop: 20,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    shadowColor: "#FFD700",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 12,
    elevation: 4,
  },
  pointsInfo: {
    flex: 1,
  },
  pointsLabel: {
    fontSize: 14,
    color: "#1A1A1A",
    marginBottom: 4,
    opacity: 0.8,
  },
  pointsValue: {
    fontSize: 24,
    fontWeight: "700",
    color: "#1A1A1A",
  },
  pointsIcon: {
    fontSize: 48,
  },
  reviewSection: {
    padding: 20,
    paddingBottom: 40,
  },
  reviewCard: {
    backgroundColor: "#667eea",
    borderRadius: 20,
    padding: 30,
    alignItems: "center",
    shadowColor: "#667eea",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.3,
    shadowRadius: 25,
    elevation: 8,
  },
  reviewIcon: {
    fontSize: 48,
    marginBottom: 16,
  },
  reviewTitle: {
    fontSize: 20,
    fontWeight: "700",
    marginBottom: 12,
    color: "#FFFFFF",
    textAlign: "center",
  },
  reviewSubtitle: {
    fontSize: 14,
    color: "#FFFFFF",
    opacity: 0.9,
    marginBottom: 24,
    textAlign: "center",
    lineHeight: 21,
  },
  starRating: {
    flexDirection: "row",
    gap: 8,
    marginBottom: 24,
  },
  star: {
    fontSize: 36,
  },
  starInactive: {
    opacity: 0.3,
  },
  reviewButton: {
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    paddingVertical: 14,
    paddingHorizontal: 28,
    marginBottom: 12,
  },
  reviewButtonText: {
    color: "#1A1A1A",
    fontSize: 15,
    fontWeight: "700",
  },
  skipButton: {
    paddingVertical: 8,
  },
  skipButtonText: {
    color: "#FFFFFF",
    fontSize: 14,
    opacity: 0.7,
  },
  bottomActions: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: "#FFFFFF",
    padding: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.1,
    shadowRadius: 20,
    elevation: 10,
    borderTopWidth: 1,
    borderTopColor: "#E8EAED",
  },
  actionButtons: {
    flexDirection: "row",
    gap: 12,
  },
  actionButton: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    padding: 16,
    borderRadius: 16,
  },
  buttonPrimary: {
    backgroundColor: "#0066FF",
    shadowColor: "#0066FF",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 12,
    elevation: 4,
  },
  buttonPrimaryText: {
    color: "#FFFFFF",
    fontSize: 15,
    fontWeight: "600",
  },
  buttonSecondary: {
    backgroundColor: "#FFFFFF",
    borderWidth: 2,
    borderColor: "#DADCE0",
  },
  buttonSecondaryText: {
    color: "#3C4043",
    fontSize: 15,
    fontWeight: "600",
  },
});
