import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#FFFFFF",
  },
  scrollContent: {
    paddingBottom: 100,
  },
  header: {
    backgroundColor: "#FFFFFF",
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: "#E8EAED",
  },
  headerTop: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 20,
  },
  headerTitle: {
    fontSize: 24,
    fontWeight: "700",
  },
  settingsButton: {
    width: 40,
    height: 40,
    backgroundColor: "#F1F3F4",
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
  },
  settingsButtonText: {
    fontSize: 18,
  },
  profileSection: {
    flexDirection: "row",
    alignItems: "center",
    gap: 16,
  },
  profileAvatar: {
    width: 70,
    height: 70,
    backgroundColor: "#FFD700",
    borderRadius: 35,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 3,
  },
  profileAvatarText: {
    fontSize: 36,
  },
  profileInfo: {
    flex: 1,
  },
  profileName: {
    fontSize: 20,
    fontWeight: "700",
    marginBottom: 4,
  },
  profileEmail: {
    fontSize: 14,
    color: "#5F6368",
    marginBottom: 8,
  },
  profileBadge: {
    backgroundColor: "#FFD700",
    color: "#1A1A1A",
    paddingVertical: 4,
    paddingHorizontal: 12,
    borderRadius: 12,
    fontSize: 12,
    fontWeight: "600",
    alignSelf: "flex-start",
  },
  pointsCard: {
    backgroundColor: "#0066FF",
    borderRadius: 16,
    padding: 24,
    margin: 20,
    shadowColor: "#0066FF",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.25,
    shadowRadius: 25,
    elevation: 8,
  },
  pointsHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
  },
  pointsLabel: {
    fontSize: 14,
    color: "#FFFFFF",
    opacity: 0.9,
  },
  pointsIcon: {
    fontSize: 24,
  },
  pointsValue: {
    fontSize: 36,
    fontWeight: "700",
    color: "#FFFFFF",
    marginBottom: 16,
  },
  pointsActions: {
    flexDirection: "row",
    gap: 8,
  },
  pointsButton: {
    flex: 1,
    backgroundColor: "rgba(255, 255, 255, 0.2)",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.3)",
    paddingVertical: 10,
    borderRadius: 10,
    alignItems: "center",
  },
  pointsButtonText: {
    color: "#FFFFFF",
    fontSize: 13,
    fontWeight: "600",
  },
  statsSection: {
    padding: 20,
    paddingBottom: 20,
  },
  statsGrid: {
    flexDirection: "row",
    gap: 12,
  },
  statCard: {
    flex: 1,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#E8EAED",
    borderRadius: 16,
    padding: 20,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 3,
  },
  statIcon: {
    fontSize: 28,
    marginBottom: 8,
  },
  statValue: {
    fontSize: 20,
    fontWeight: "700",
    color: "#0066FF",
    marginBottom: 4,
  },
  statLabel: {
    fontSize: 12,
    color: "#5F6368",
  },
  menuSection: {
    padding: 20,
    paddingBottom: 20,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "700",
    marginBottom: 12,
    color: "#1A1A1A",
  },
  menuList: {
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#E8EAED",
    borderRadius: 16,
    overflow: "hidden",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 3,
  },
  menuItem: {
    flexDirection: "row",
    alignItems: "center",
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#F1F3F4",
  },
  menuItemLast: {
    borderBottomWidth: 0,
  },
  menuIcon: {
    width: 40,
    height: 40,
    backgroundColor: "#F1F3F4",
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 16,
  },
  menuIconFeatured: {
    backgroundColor: "#0066FF",
  },
  menuIconText: {
    fontSize: 20,
  },
  menuContent: {
    flex: 1,
  },
  menuTitle: {
    fontSize: 16,
    fontWeight: "600",
    marginBottom: 4,
  },
  menuSubtitle: {
    fontSize: 13,
    color: "#5F6368",
  },
  menuBadge: {
    backgroundColor: "#FFD700",
    color: "#1A1A1A",
    paddingVertical: 4,
    paddingHorizontal: 8,
    borderRadius: 8,
    fontSize: 11,
    fontWeight: "700",
    marginLeft: 8,
  },
  menuArrow: {
    color: "#DADCE0",
    fontSize: 18,
    marginLeft: 8,
  },
  orderHistorySection: {
    padding: 20,
    paddingBottom: 20,
  },
  orderHistoryHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  viewAllButton: {
    fontSize: 14,
    color: "#5F6368",
  },
  orderCard: {
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#E8EAED",
    borderRadius: 16,
    padding: 16,
    marginBottom: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 3,
  },
  orderHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#F1F3F4",
  },
  orderDate: {
    fontSize: 14,
    color: "#5F6368",
  },
  orderStatus: {
    backgroundColor: "#E8EAED",
    color: "#3C4043",
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 12,
    fontSize: 12,
    fontWeight: "600",
  },
  orderItems: {
    marginBottom: 12,
  },
  orderItemName: {
    fontSize: 15,
    fontWeight: "600",
    marginBottom: 4,
  },
  orderItemDetail: {
    fontSize: 13,
    color: "#5F6368",
  },
  orderFooter: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  orderNumber: {
    fontSize: 13,
    color: "#5F6368",
  },
  orderTotal: {
    fontSize: 18,
    fontWeight: "700",
    color: "#0066FF",
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "flex-end",
  },
  modalContent: {
    backgroundColor: "#FFFFFF",
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    maxHeight: "80%",
  },
  modalHeader: {
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: "#E8EAED",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: "700",
  },
  modalClose: {
    width: 32,
    height: 32,
    backgroundColor: "#F1F3F4",
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
  },
  modalCloseText: {
    fontSize: 20,
  },
  modalBody: {
    padding: 20,
  },
  paymentCard: {
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#E8EAED",
    borderRadius: 16,
    padding: 16,
    marginBottom: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 3,
  },
  paymentInfo: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  paymentIcon: {
    width: 50,
    height: 50,
    backgroundColor: "#FFD700",
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  paymentIconText: {
    fontSize: 24,
  },
  paymentDetails: {
    flex: 1,
  },
  paymentName: {
    fontSize: 15,
    fontWeight: "600",
    marginBottom: 4,
    flexDirection: "row",
    alignItems: "center",
  },
  paymentDefault: {
    backgroundColor: "#0066FF",
    color: "#FFFFFF",
    paddingVertical: 4,
    paddingHorizontal: 10,
    borderRadius: 8,
    fontSize: 11,
    fontWeight: "600",
    marginLeft: 8,
  },
  paymentNumber: {
    fontSize: 13,
    color: "#5F6368",
  },
  paymentActions: {
    flexDirection: "row",
    gap: 8,
  },
  iconButton: {
    width: 36,
    height: 36,
    backgroundColor: "#F1F3F4",
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
  },
  iconButtonText: {
    fontSize: 16,
  },
  addPaymentButton: {
    width: "100%",
    backgroundColor: "#FFFFFF",
    borderWidth: 2,
    borderColor: "#DADCE0",
    borderStyle: "dashed",
    borderRadius: 16,
    padding: 16,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  addPaymentButtonText: {
    fontSize: 15,
    fontWeight: "600",
    color: "#5F6368",
  },
});
